name: Generate Repo Diagram

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Diagram
      uses: githubocto/repo-visualizer@0.7.1
      with:
        output_file: diagram.svg
        artifact_name: my-diagram

    - name: Download Diagram Artifact
      uses: actions/download-artifact@v3
      with:
        name: my-diagram
        path: src/assets/images
